USE ONLINE_SELF_IMPROVEMENT;

--DROP PROCEDURE DeleteMeeting;
GO
CREATE PROCEDURE DeleteMeeting
	@MeetingID SMALLINT
AS 
BEGIN 
	SET NOCOUNT ON
	DELETE FROM Meeting WHERE @MeetingID=Meeting.ID;
END
GO